name: 'Kedify HTTP Add-on release trigger'

on:
  workflow_dispatch:
    inputs:
      upstreamTag:
        description: 'Upstream KEDA HTTP Add-on tag to release Kedify HTTP Add-on images from'
        required: true
        default: 'v0.8.0'
jobs:
  tag_kedify_release:
    secrets: inherit
    uses: kedify/github-meta/.github/workflows/kedify-release-trigger.yml@main
    with:
      upstreamTag: ${{ inputs.upstreamTag }}
      repoName: http-add-on
